#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

PRES_NAME="adv_alui"

#pandoc ${PRES_NAME}.md -t beamer -s -o ${PRES_NAME}.tex
#pandoc ${PRES_NAME}.md -t beamer --natbib -s -o ${PRES_NAME}.tex
#pandoc ${PRES_NAME}.md -t beamer -V theme:alui --natbib -s -o ${PRES_NAME}.tex


echo "Compiling stuff..."
pdflatex ${PRES_NAME}.tex 
bibtex *.aux
pdflatex ${PRES_NAME}.tex
pdflatex ${PRES_NAME}.tex

echo "Removing stuff..."
rm -f ${PRES_NAME}.{log,aux,nav,out,snm,toc,bbl,blg,vrb}
#rm -f ${PRES_NAME}.tex

