gen_default_init = function(y, prior, K=10, L0=10, L1=10) {
  #' Generate default init
  #' @example init = gen_default_init(y, prior, K=10, L0=10, L1=10)
  #' @param y: list of matrices
  #' @param prior: list of prior hyper-parameters (generated by gen_default prior)
  #' @export
  I = length(y)
  J = NCOL(y[[1]])
  N = lapply(y, NROW)
  list(
    beta_0    = rep(prior$m_beta0),
    beta_1    = rep(prior$a_beta1 / prior$b_beta1),
    missing_y = y,
    mus_0     = rep(prior$psi_0, L0),
    mus_1     = rep(prior$psi_1, L1),
    sig2_0    = matrix(1, I, L0),
    sig2_1    = matrix(1, I, L1),
    s         = rep(prior$a_s / prior$b_s, I),
    gam       = lapply(N, function(Ni) matrix(0, nrow=Ni, ncol=J)),
    eta_0     = array(1 / L0, c(I,J,L0)),
    eta_1     = array(1 / L1, c(I,J,L1)),
    v         = rep(1/K, K),
    alpha     = 1.0,
    H         = matrix(0, J, K),
    lam       = lapply(N, function(Ni) double(Ni)),
    W         = matrix(1/K, I, K)
  ) 
}
