gen_default_locked = function(init) {
  #' Generate default locked (aka fixed) parameters (bool)
  #' @examples locked = gen_default_locked(init)
  #' @param init: list of initial values (generated by gen_default_init)
  #' @export
  lapply(init, function(i) FALSE)
}
