gen_default_fixed = function(init) {
  #' Generate default fixed parameters (bool)
  #' @example fixed = gen_default_fixed(init)
  #' @param init: list of initial values (generated by gen_default_init)
  #' @export
  lapply(init, function(i) FALSE)
}
