# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_cytof3_rcpparma_hello_world', PACKAGE = 'cytof3')
}

rcpparma_outerproduct <- function(x) {
    .Call('_cytof3_rcpparma_outerproduct', PACKAGE = 'cytof3', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_cytof3_rcpparma_innerproduct', PACKAGE = 'cytof3', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_cytof3_rcpparma_bothproducts', PACKAGE = 'cytof3', x)
}

hi_with_auto <- function() {
    invisible(.Call('_cytof3_hi_with_auto', PACKAGE = 'cytof3'))
}

