# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' big matrix to list of matrices
#' TODO: Check
#' @export
bigmat_to_listmat <- function(Y, N) {
    .Call('_cytof3_bigmat_to_listmat', PACKAGE = 'cytof3', Y, N)
}

test_gen_data_obj <- function(y) {
    .Call('_cytof3_test_gen_data_obj', PACKAGE = 'cytof3', y)
}

#' Cytof3 Unit Tests
#' @export
cytof3_unit_tests_cpp <- function() {
    invisible(.Call('_cytof3_cytof3_unit_tests_cpp', PACKAGE = 'cytof3'))
}

#' Cytof Model for fixed K
#' @export
cytof_fix_K_fit <- function(y, B, burn, warmup = 100L, thin = 1L, thin_K = 5L, compute_loglike_every = 1L, print_freq = 10L, ncores = 1L, show_timings = FALSE, prop_for_training = .05, shuffle_data = FALSE, normalize_loglike = FALSE, prior_input = NULL, truth_input = NULL, init_input = NULL) {
    .Call('_cytof3_cytof_fix_K_fit', PACKAGE = 'cytof3', y, B, burn, warmup, thin, thin_K, compute_loglike_every, print_freq, ncores, show_timings, prop_for_training, shuffle_data, normalize_loglike, prior_input, truth_input, init_input)
}

#' Shuffle matrix by rows
#' @export
shuffle_mat <- function(X) {
    .Call('_cytof3_shuffle_mat', PACKAGE = 'cytof3', X)
}

