# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export Bar
NULL

#' @export Foo
NULL

test_gen_data_obj <- function(y) {
    .Call('_cytof3_test_gen_data_obj', PACKAGE = 'cytof3', y)
}

#' Cytof3 Unit Tests
#' @export
cytof3_unit_tests_cpp <- function() {
    invisible(.Call('_cytof3_cytof3_unit_tests_cpp', PACKAGE = 'cytof3'))
}

#' Cytof Model for fixed K
#' TODO: add descriptions for params
#' @export
fit_cytof_cpp <- function(y, B, burn, prior_ls, fixed_ls, init_ls, thin = 1L, thin_some = 5L, compute_loglike_every = 1L, print_freq = 10L, ncores = 1L, show_timings = FALSE, prop_for_training = .05, shuffle_data = FALSE, normalize_loglike = FALSE) {
    .Call('_cytof3_fit_cytof_cpp', PACKAGE = 'cytof3', y, B, burn, prior_ls, fixed_ls, init_ls, thin, thin_some, compute_loglike_every, print_freq, ncores, show_timings, prop_for_training, shuffle_data, normalize_loglike)
}

#' Shuffle matrix by rows
#' @export
shuffle_mat <- function(X) {
    .Call('_cytof3_shuffle_mat', PACKAGE = 'cytof3', X)
}

