#!/bin/bash

#PBS -N cytof 
#PBS -S /bin/bash 
#PBS -l nodes=4
#PBS -l walltime=2:00:00 
#PBS -q newest 
#PBS -V
#PBS -o output.log
#PBS -e error.log

# change dir to current submission dir
cd $PBS_O_WORKDIR

#Rscript test_cytof_fix_K_simdat.R

date
for i in `seq 4`
do
  echo $i
  sleep 10 &
done
wait
date

# to submit: qsub job
