#!/bin/bash

### SIMULATION ON LOGIN / INTERACTIVE NODE OF SERVER
K="-1 0 1"

### TEST SIM
for k in $K
do
  i=0
  echo "i:$i, k:$k"
  Rscript test_cytof_fix_K_simdat.R $i $k &
done
wait

### BIG SIMS
date
for k in $K
do
  for i in `seq 1 4`
  do
    echo "i:$i, k:$k"
    Rscript test_cytof_fix_K_simdat.R $i $k &
  done
done
wait
date

#Rscript test_cytof_fix_K_simdat.R 3 -1
