#!/usr/bin/env python3

from urllib.request import urlretrieve
import re

getID = re.compile("id=.*")

def driveLink2Download(dlink):
    header = "https://docs.google.com/uc?export=download&"
    ID = getID.findall(dlink)[0]
    url_download = header + ID
    urlretrieve(url_download, "img.zip")

if __name__ == "__main__":
    imgDate = "2018-06-07"
    latestImg = "https://drive.google.com/open?id=1-AgrM40_ohrffwd2Uj2oMslxU0TGx0g4"

    print("Downloading latest images from: {}".format(imgDate))
    driveLink2Download(latestImg)
