#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc report12Aug17.md -s -o report12Aug17.tex

pdflatex report12Aug17.tex
bibtex report12Aug17.aux
pdflatex report12Aug17.tex
pdflatex report12Aug17.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f report12Aug17.tex

