#!/bin/bash

### PARAMETERS FOR PARALLEL JOB ###
MAX_CORES=4

### Rscript Params ###
N=100
NCORES=1
B=2000
BURN=1000
K_MCMC=10
K_TRUE=4
RFAM="FALSE TRUE"

### Environment Variables ###
export OPENBLAS_NUM_THREADS=1

for rfam in $RFAM; do
  ### Simulation Study ###
  i=$((i+1)) 

  # ADD BACKSLASH AT THE END!
  outdir="../out/sim_rand_beta_K${K_MCMC}_N${N}_repFam-${rfam}/"

  mkdir -p $outdir
  cmd="Rscript sim.R --N=$N --ncores=$NCORES --B=$B --burn=$BURN -o $outdir --K_MCMC=$K_MCMC --K_TRUE=$K_TRUE --J=5 --use_repulsive=$rfam --repFAM_Test=TRUE"
  cmd="$cmd > ${outdir}log.txt"
  sem -j $MAX_CORES $cmd
  echo "Simulation $i: $outdir"
done
