#!/bin/bash

### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=4

### Rscript Params ###
N="100 1000 10000"
NCORES=1
B=2000
BURN=1000

### Environment Variables ###
export OPENBLAS_NUM_THREADS=1

### Simulation Study ###
for n in $N; do
  i=$((i+1)) 

  # ADD BACKSLASH AT THE END!
  outdir="../out/sim_locked_beta1_K20_N${n}/"

  mkdir -p $outdir
  cmd="Rscript sim.R --N=$n --ncores=$NCORES --B=$B --burn=$BURN -o $outdir"
  cmd="$cmd > ${outdir}log.txt"
  sem -j $MAX_CORES $cmd
  echo "Simulation $i: $outdir"
done
