#!/bin/bash

### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=4

### Rscript Params ###
N=500
NCORES=1
B=2000
BURN=1000
USE_REPULSIVE="FALSE"
K="5 10 20"

### Environment Variables ###
export OPENBLAS_NUM_THREADS=1

### Simulation Study ###
for k in $K; do
  i=$((i+1)) 

  # ADD BACKSLASH AT THE END!
  outdir="../out/sim_rand_beta_K20_N${N}_sensK${k}/"

  mkdir -p $outdir
  cmd="Rscript sim.R --N=$N --ncores=$NCORES --B=$B --burn=$BURN -o $outdir --use_repulsive=$USE_REPULSIVE --K_MCMC=$k"
  cmd="$cmd > ${outdir}log.txt"
  sem -j $MAX_CORES $cmd
  echo "Simulation $i: $outdir"
done
