#!/bin/bash

#SIM_NAME="fixedPsiWrong"
#K="-1 0 1"
#
#for k in $K
#do
#  for i in `seq 4`
#  do
#    #echo "./genReport.py ${SIM_NAME}_K${k}_sim${i}"
#    ./genReport.py ${SIM_NAME}_K${k}_sim${i}
#  done
#done

# Generate report for all dirs in out
OUTDIR='../out'
for f in `ls $OUTDIR`
do
  ./genReport.py $f
done

echo "Compile PDFs? (y/n)"
read COMPILE_PDFS 
echo

compile_stuff () {
  d=$1
  cd $d
  ./compile ${d}.md
  cd ../
}

if [ "$COMPILE_PDFS" = "y" ]
then
  cd report
  ds=`ls`

  for d in $ds
  do
    compile_stuff $d #&
  done
  wait
fi
