#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name
# --number-sections => numbers section headings

# includes all <include file="file/to/include.txt">
# see github.com/luiarthur/myBin/md-include.py
md-include.py sampling.md

pandoc .sampling-tmp.md -s --natbib -o sampling.tex --number-sections
rm -f .sampling-tmp.md

pdflatex sampling.tex
bibtex sampling.aux
pdflatex sampling.tex
pdflatex sampling.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f sampling.tex

