#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name
# --number-sections => numbers section headings

pandoc sampling.md -s --natbib -o sampling.tex --number-sections

pdflatex sampling.tex
bibtex sampling.aux
pdflatex sampling.tex
pdflatex sampling.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
#rm -f sampling.tex

