#!/bin/bash

### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=4

### Rscript Params ###
N=500
NCORES=1
B=2000
BURN=1000
USE_REPULSIVE="FALSE"
K="5 10 20"

### Environment Variables ###
export OPENBLAS_NUM_THREADS=1

### Simulation Study ###
for k in $K; do
  i=$((i+1)) 

  # ADD BACKSLASH AT THE END!
  outdir="../../out/sim_locked_beta1_K20_N${N}_sensK${k}/"

  cmd="Rscript separate_pp_obs.R $outdir"
  cmd="$cmd > ${outdir}/log_plots.txt"
  sem -j $MAX_CORES $cmd
  echo "Simulation $i: $outdir"
done
