// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// missing_R
bool missing_R(const std::vector<arma::mat>& y, int i, int n, int j);
RcppExport SEXP cytof2_missing_R(SEXP ySEXP, SEXP iSEXP, SEXP nSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(missing_R(y, i, n, j));
    return rcpp_result_gen;
END_RCPP
}
// cytof_fix_K_fit
std::vector<List> cytof_fix_K_fit(const std::vector<arma::mat>& y, int B, int burn, int warmup, int thin, int thin_K, int compute_loglike_every, int print_freq, int ncores, bool show_timings, double prop_for_training, bool shuffle_data, bool normalize_loglike, Nullable<List> prior_input, Nullable<List> truth_input, Nullable<List> init_input);
RcppExport SEXP cytof2_cytof_fix_K_fit(SEXP ySEXP, SEXP BSEXP, SEXP burnSEXP, SEXP warmupSEXP, SEXP thinSEXP, SEXP thin_KSEXP, SEXP compute_loglike_everySEXP, SEXP print_freqSEXP, SEXP ncoresSEXP, SEXP show_timingsSEXP, SEXP prop_for_trainingSEXP, SEXP shuffle_dataSEXP, SEXP normalize_loglikeSEXP, SEXP prior_inputSEXP, SEXP truth_inputSEXP, SEXP init_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type thin_K(thin_KSEXP);
    Rcpp::traits::input_parameter< int >::type compute_loglike_every(compute_loglike_everySEXP);
    Rcpp::traits::input_parameter< int >::type print_freq(print_freqSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< bool >::type show_timings(show_timingsSEXP);
    Rcpp::traits::input_parameter< double >::type prop_for_training(prop_for_trainingSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle_data(shuffle_dataSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize_loglike(normalize_loglikeSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type prior_input(prior_inputSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type truth_input(truth_inputSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type init_input(init_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cytof_fix_K_fit(y, B, burn, warmup, thin, thin_K, compute_loglike_every, print_freq, ncores, show_timings, prop_for_training, shuffle_data, normalize_loglike, prior_input, truth_input, init_input));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_mat
arma::mat shuffle_mat(arma::mat X);
RcppExport SEXP cytof2_shuffle_mat(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_mat(X));
    return rcpp_result_gen;
END_RCPP
}
// unit_tests
void unit_tests();
RcppExport SEXP cytof2_unit_tests() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    unit_tests();
    return R_NilValue;
END_RCPP
}
