// Generated by `generate.py`. Don't edit by hand!
#include <RcppArmadillo.h>
using namespace Rcpp;

//' @export Prior
struct Prior {
  // missing mechnism. constants
  double c1;
  double c2;
  double c3;
  double c4;
  double c5;
  double c6;
  double c7;
  double c8;
  Prior(double c1_, double c2_, double c3_, double c4_, double c5_, double c6_, double c7_, double c8_) : c1(c1_), c2(c2_),c3(c3_),c4(c4_),c5(c5_),c6(c6_),c7(c7_),c8(c8_) {}
};


RCPP_MODULE(Cytof_Module) {
    
  class_<Prior>("Prior")
    .constructor<double, double, double, double, double, double, double, double>()
    .field("c1", &Prior::c1)
    .field("c2", &Prior::c2)
    .field("c3", &Prior::c3)
    .field("c4", &Prior::c4)
    .field("c5", &Prior::c5)
    .field("c6", &Prior::c6)
    .field("c7", &Prior::c7)
    .field("c8", &Prior::c8)
  ;

}
