// Generated by `generate.py`. Don't edit by hand!
#include "Prior_addon.h"
#include "State_addon.h"
#include "Fixed_addon.h"

#include <Rcpp.h>
using namespace Rcpp;

//RCPP_MODULE(Cytof_Module) {
//    
//  class_<Prior>("Prior")
//    .constructor<double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, arma::mat, double, int>()
//    .field("c0", &Prior::c0)
//    .field("c1", &Prior::c1)
//    .field("m_beta0", &Prior::m_beta0)
//    .field("s2_beta0", &Prior::s2_beta0)
//    .field("cs_beta0", &Prior::cs_beta0)
//    .field("a_beta1", &Prior::a_beta1)
//    .field("b_beta1", &Prior::b_beta1)
//    .field("cs_beta1", &Prior::cs_beta1)
//    .field("psi_0", &Prior::psi_0)
//    .field("psi_1", &Prior::psi_1)
//    .field("tau2_0", &Prior::tau2_0)
//    .field("tau2_1", &Prior::tau2_1)
//    .field("a_sig", &Prior::a_sig)
//    .field("a_s", &Prior::a_s)
//    .field("b_s", &Prior::b_s)
//    .field("a_eta0", &Prior::a_eta0)
//    .field("a_eta1", &Prior::a_eta1)
//    .field("a_alpha", &Prior::a_alpha)
//    .field("b_alpha", &Prior::b_alpha)
//    .field("cs_h", &Prior::cs_h)
//    .field("G", &Prior::G)
//    .field("d_W", &Prior::d_W)
//    .field("K", &Prior::K)
//  ;
//
//  class_<State>("State")
//    .constructor<arma::vec, arma::vec, std::vector<Rcpp::NumericMatrix>, arma::vec, arma::vec, arma::mat, arma::mat, arma::vec, std::vector<Rcpp::IntegerMatrix>, arma::cube, arma::cube, arma::vec, double, arma::mat, std::vector<Rcpp::IntegerVector>, arma::mat>()
//    .field("beta_0", &State::beta_0)
//    .field("beta_1", &State::beta_1)
//    .field("missing_y", &State::missing_y)
//    .field("mus_0", &State::mus_0)
//    .field("mus_1", &State::mus_1)
//    .field("sig2_0", &State::sig2_0)
//    .field("sig2_1", &State::sig2_1)
//    .field("s", &State::s)
//    .field("gam", &State::gam)
//    .field("eta_0", &State::eta_0)
//    .field("eta_1", &State::eta_1)
//    .field("v", &State::v)
//    .field("alpha", &State::alpha)
//    .field("H", &State::H)
//    .field("lam", &State::lam)
//    .field("W", &State::W)
//  ;
//
//  class_<Fixed>("Fixed")
//    .constructor<bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool>()
//    .field("beta_0", &Fixed::beta_0)
//    .field("beta_1", &Fixed::beta_1)
//    .field("missing_y", &Fixed::missing_y)
//    .field("mus_0", &Fixed::mus_0)
//    .field("mus_1", &Fixed::mus_1)
//    .field("sig2_0", &Fixed::sig2_0)
//    .field("sig2_1", &Fixed::sig2_1)
//    .field("s", &Fixed::s)
//    .field("gam", &Fixed::gam)
//    .field("eta_0", &Fixed::eta_0)
//    .field("eta_1", &Fixed::eta_1)
//    .field("v", &Fixed::v)
//    .field("alpha", &Fixed::alpha)
//    .field("H", &Fixed::H)
//    .field("lam", &Fixed::lam)
//    .field("W", &Fixed::W)
//  ;
//
//}
