// Generated by `gen_module.py`. Don't edit by hand!
#ifndef FIXED_ADDON_H
#define FIXED_ADDON_H

#include <Rcpp.h>

//' @export Fixed
struct Fixed {
  bool beta_0 = false;
  bool beta_1 = false;
  bool missing_y = false;
  bool mus_0 = false;
  bool mus_1 = false;
  bool sig2_0 = false;
  bool sig2_1 = false;
  bool s = false;
  bool gam = false;
  bool eta_0 = false;
  bool eta_1 = false;
  bool v = false;
  bool alpha = false;
  bool H = false;
  bool lam = false;
  bool W = false;

  Fixed(bool beta_0_, bool beta_1_, bool missing_y_, bool mus_0_, bool mus_1_, bool sig2_0_, bool sig2_1_, bool s_, bool gam_, bool eta_0_, bool eta_1_, bool v_, bool alpha_, bool H_, bool lam_, bool W_) : beta_0(beta_0_), beta_1(beta_1_), missing_y(missing_y_), mus_0(mus_0_), mus_1(mus_1_), sig2_0(sig2_0_), sig2_1(sig2_1_), s(s_), gam(gam_), eta_0(eta_0_), eta_1(eta_1_), v(v_), alpha(alpha_), H(H_), lam(lam_), W(W_) {}
};


#endif
