#!/bin/bash

numArgs=$#

if [ $numArgs == 0 ]
then
  echo "Usage:"
  echo "        $ ./cpJuhee <VERSION_NUMBER>"
  exit 1
fi

ddmmmyy=`date +%d%b%Y`
VERSION_NUMBER=$1

cp sampling.tex juhee/sampling_v${VERSION_NUMBER}_${ddmmmyy}.tex
