#!/bin/bash

simImgPath="../../../src/model3/sims/out/"
simName="sim_locked_beta1_K20_N10000/"
outdir="img/sim/"

#simName="locked_beta1_K20/"
#outdir="img/cb/"

mkdir -p $outdir

I="1 2 3"
for i in $I; do
  #pdfPage ${imgPath}/${simName}/"Z_true_byW.pdf" $i
  #mv ${imgPath}/${simName}/"Z_true_byW_p${i}.pdf" img/

  cp ${simImgPath}/${simName}/"Z_true_all.pdf" $outdir
  cp ${simImgPath}/${simName}/"YZ00${i}.png" $outdir
  cp ${simImgPath}/${simName}/"Y00${i}.png" $outdir
  cp ${simImgPath}/${simName}/"Ysorted00${i}.png" $outdir
  cp ${simImgPath}/${simName}/"y_hist.pdf" $outdir
  cp ${simImgPath}/${simName}/"sim.R" $outdir
done
