# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' parRngTest
#' @export
parRngTest <- function(N = 10000L, NUM_THREADS = 8L) {
    invisible(.Call('_parRng_parRngTest', PACKAGE = 'parRng', N, NUM_THREADS))
}

