#!/bin/bash
#!/bin/bash
#PBS -S /bin/bash
#PBS -N Cytof_cb
#PBS -l nodes=1:ppn=16
#PBS -l walltime=10:00:00:00
#PBS -V

### THIS SCRIPT REQUIRES GNU PARALLEL: sem ###

### To use compute node on grape: qsub analyze_cb_randomK

### Go to work directory at submission time if using a compute node on grape
if [[ $HOSTNAME == *"grape"* || $HOSTNAME == *"compute"* ]]
then
  cd $PBS_O_WORKDIR
fi


### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=32

### PARAMETERS FOR MCMC ###
DATA_DIR="dat/cytof_cb.RData"
MCMC_K="5 10 16" #"16"
OUTDIR="out/cb_fixedK/"
B=2000
BURN="5000"
THIN=1
PROP=0 #"0.5 0.7 0.9"
NCORES=16
WARMUP=1000

for p in $PROP
do
  for k in $MCMC_K
  do
    i=$(( i + 1 ))
    outdir="${OUTDIR}/cb_k${k}_B${B}_burn${BURN}_thin${THIN}_prop${p}/"
    cmd="nice Rscript realDat_cb_randomK.R $DATA_DIR $k $outdir $B $BURN $THIN $p $WARMUP $NCORES"
    sem -j $MAX_CORES $cmd
    echo "Simulation $i: $outdir"
  done
done
sem --wait
