#!/bin/bash

### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=15


### PARAMETERS FOR MCMC ###
DATA_DIR="dat/cytof_cb.RData"
MCMC_K="2 3 4 5 6 7 8 9 10"
OUTDIR="out/cb"
B=200
BURN="20 100 500"
THIN=5

for k in $MCMC_K
do
  for burn in $BURN
  do
    i=$((i+1)) 
    outdir="${OUTDIR}/cb_k${k}_B${B}_burn${burn}_thin${THIN}/"

    Rscript realDat_cb.R $DATA_DIR $k $outdir $B $burn $THIN &

    if  [[ $(( i % MAX_CORES )) == 0 ]]; then wait; fi
  done
done
