#!/bin/bash
# Requires GNU Parallel: sem

### PARAMETERS FOR PARALLEL JOB ###
MAX_CORES=15

### PARAMETERS FOR MCMC ###
DATA_DIR="dat/cytof_cb.RData"
MCMC_K="2 3 4 5 6 7 8 9 10"
OUTDIR="out/cb"
B=200
BURN="100 500 1000"
THIN=5

for burn in $BURN
do
  for k in $MCMC_K
  do
    outdir="${OUTDIR}/cb_k${k}_B${B}_burn${burn}_thin${THIN}/"
    cmd="Rscript realDat_cb.R $DATA_DIR $k $outdir $B $burn $THIN"
    echo $outdir
    sem --citation -j $MAX_CORES $cmd
  done
done
sem --wait
