#!/bin/bash
# Requires GNU Parallel: sem

### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=32

### PARAMETERS FOR MCMC ###
DATA_DIR="dat/cytof_cb.RData"
MCMC_K="16"
OUTDIR="out/cb_randomK_new"
B=2000
BURN="2000"
THIN=1
PROP="0.5 0.7 0.9"
NCORES=16
WARMUP=1000

for $p in $PROP
do
  for k in $MCMC_K
  do
    i=$(( i + 1 ))
    outdir="${OUTDIR}/cb_k${k}_B${B}_burn${BURN}_thin${THIN}_prop${p}/"
    cmd="nice Rscript realDat_cb_randomK.R $DATA_DIR $k $outdir $B $BURN $THIN $p $WARMUP $NCORES"
    sem -j $MAX_CORES $cmd
    echo "Simulation $i: $outdir"
  done
done
sem --wait
