#!/bin/bash

K="3 4 7"
OUTDIR="out/sim2/"
reportDir="../../../tex/model2/report/img/"
BURN=6000
B=2000
THIN=1
N=10000

### Move W_truth ###
cp $OUTDIR/j32_k4_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/W_truth.tex $reportDir/simple


### Move Simple Data ###
cp $OUTDIR/j32_k4_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/rawDat*.png $reportDir/complex

### Move Complex Data ###
cp $OUTDIR/j32_k4_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/rawDat*.png $reportDir/simple

### Move True Z ###
pdfPage $OUTDIR/j32_k4_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params.pdf 7
pdfPage $OUTDIR/j32_k4_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params.pdf 7
mv $OUTDIR/j32_k4_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params_p7.pdf $reportDir/complex/trueZ.pdf
mv $OUTDIR/j32_k4_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params_p7.pdf $reportDir/simple/trueZ.pdf

### Move True prob missing  ###
cp $OUTDIR/j32_k4_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/prior_prob_miss.pdf $reportDir/complex/
cp $OUTDIR/j32_k4_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/prior_prob_miss.pdf $reportDir/simple/


for k in $K
do

  ### Move W_mean ###
  cp $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/W_mean.tex $reportDir/complex/W_mean_k${k}.tex
  cp $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/W_mean.tex $reportDir/simple/W_mean_k${k}.tex

  # move mus posterior
  pdfPage $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params.pdf 18
  pdfPage $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params.pdf 18

  mv $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params_p18.pdf $reportDir/complex/mus_k${k}.pdf
  mv $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params_p18.pdf $reportDir/simple/mus_k${k}.pdf

  # move Z posterior mean
  pdfPage $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params.pdf 3
  pdfPage $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params.pdf 3

  mv $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params_p3.pdf $reportDir/complex/Z_k${k}.pdf
  mv $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params_p3.pdf $reportDir/simple/Z_k${k}.pdf

  # move Z pointest
  pdfPage $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params.pdf 5
  pdfPage $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params.pdf 5

  mv $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params_p5.pdf $reportDir/complex/Z_point_k${k}.pdf
  mv $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params_p5.pdf $reportDir/simple/Z_point_k${k}.pdf

  # move imputed y
  pdfPage $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params.pdf 28-39
  pdfPage $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params.pdf 28-39

  mv $OUTDIR/j32_k${k}_N${N}_z0_B${B}_burn${BURN}_thin${THIN}/params_p28-39.pdf $reportDir/complex/imputed${k}.pdf
  mv $OUTDIR/j32_k${k}_N${N}_z1_B${B}_burn${BURN}_thin${THIN}/params_p28-39.pdf $reportDir/simple/imputed${k}.pdf
done
