#!/bin/bash
#PBS -S /bin/bash
#PBS -N Cytof_Sim2
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -V

### THIS SCRIPT REQUIRES GNU PARALLEL: sem ###

### To use compute node on grape: qsub sim2
### To use interactive node (muscat, jerez, mencia) instead, do: ./sim2

### Go to work directory at submission time if using a compute node on grape
if [[ $HOSTNAME == *"grape"* || $HOSTNAME == *"compute"* ]]
then
  cd $PBS_O_WORKDIR
fi


### PARAMETERS FOR PARALLEL JOB ###
i=0
MAX_CORES=8

### PARAMETERS FOR MCMC ###
J=32
MCMC_K_INIT="1 10"
N="10000"
USE_SIMPLE_Z="0 1"
PROP="0.5  0.7  0.3  0.9  0.1"
NCORES=8
OUTDIR='out/simRandomK/'

B=2000
BURN=1200 #max time 12 hrs.
THIN=5

for j in $J
do
  for k in $MCMC_K_INIT
  do
    for n in $N
    do
      for z in $USE_SIMPLE_Z
      do
        for p in $PROP
        do
          i=$((i+1)) 
          outdir="${OUTDIR}/j${j}_k${k}_N${n}_z${z}_B${B}_burn${BURN}_thin${THIN}/"
          cmd="Rscript simRandomK.R --J=$j --mcmc_k_init=$k --data_size=$n --use_simple_z=$z --outdir=$outdir --b=$B --burn=$BURN --thin=$THIN --prop_train=$p --ncores=$NCORES"
          mkdir -p $outdir
          sem -j $MAX_CORES $cmd > ${outdir}log.txt
          #echo "Simulation $i: $outdir"
        done
      done
    done
  done
done
sem --wait

