#PBS -S /bin/bash
#PBS -N Cytof Test
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -V


### Go to work directory at submission time
cd $PBS_O_WORKDIR

### Sample Sizes
N="100 1000 10000"
K="2 4 6 8 10"
MAX_CORES=16

for n in $N
do
  for k in $K
  do
    outdir="out/timings/N${n}_K${k}/"
    sem -j $MAX_CORES "Rscript simple.R 32 $k $n 1 $outdir 100 900 1"
  done
done
sem --wait


### To submit:
# qsub timing.pbs
