#!/bin/bash

SERVER="alui2@firedance"
DIR="repo/ucsc_litreview/cytof/src/test/test_cytof_fix_K_simdat/out"

#rsync -av $SERVER:~/$DIR/ out/ --exclude data.pdf --exclude *.RData
rsync -av $SERVER:~/$DIR/ out/ --exclude *.RData

#sftp alui2@firedance.soe.ucsc.edu <<EOF 
#  get -r repo/ucsc_litreview/cytof/src/test/test_cytof_fix_K_simdat/out 
#EOF
