#!/bin/bash

### Generate the docs ###
#R -e "roxygen2::roxygenise('cytof2')"
#R -e "Rcpp::compileAttributes('cytof2')"
R -e "roxygen2::roxygenise('cytof2');Rcpp::compileAttributes('cytof2');"

##### Install Package Locally ###
#R CMD REMOVE cytof2
rm -f cytof2_*
R CMD build cytof2 
R CMD INSTALL cytof2*.tar.gz

