#!/bin/bash

### Generate the docs ###
cd cytof2
R -e "Rcpp::compileAttributes(); roxygen2::roxygenise();"
cd ..

### Install Package Locally ###
#R CMD REMOVE cytof2
R CMD build cytof2
R CMD INSTALL cytof2*.tar.gz

