// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// parRngTest
void parRngTest(int N, int NUM_THREADS, int m);
RcppExport SEXP _parRng_parRngTest(SEXP NSEXP, SEXP NUM_THREADSSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type NUM_THREADS(NUM_THREADSSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    parRngTest(N, NUM_THREADS, m);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parRng_parRngTest", (DL_FUNC) &_parRng_parRngTest, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_parRng(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
