#!/bin/bash

f="cytof3/src/fit_cytof"

g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/arthur/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/arthur/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include" -I"/home/arthur/R/x86_64-pc-linux-gnu-library/3.4/RcppTN/include"   -fopenmp  -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c ${f}.cpp -o ${f}.o

#g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/arthur/lib/R_lib/Rcpp/include" -I"/home/arthur/lib/R_lib/RcppArmadillo/include" -I"/home/arthur/lib/R_lib/RcppTN/include"   -fopenmp  -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c ${f}.cpp -o ${f}.o
