#!/bin/bash

f="cytof3/src/fit_cytof"

### Original compile script
#time g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/arthur/lib/R_lib/Rcpp/include" -I"/home/arthur/lib/R_lib/RcppArmadillo/include" -I"/home/arthur/lib/R_lib/RcppTN/include"   -fopenmp  -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c ${f}.cpp -o ${f}.o

### Compile script with some flags removed (for speed)
time g++ -std=gnu++11 -I/usr/share/R/include -I"/home/arthur/lib/R_lib/Rcpp/include" -I"/home/arthur/lib/R_lib/RcppArmadillo/include" -I"/home/arthur/lib/R_lib/RcppTN/include"   -c ${f}.cpp -o ${f}.o
