#!/bin/bash

MODEL_NAME="cytof3"

### Generate the docs ###
rm -f ${MODEL_NAME}/NAMESPACE
R -q -e "roxygen2::roxygenise('${MODEL_NAME}');Rcpp::compileAttributes('${MODEL_NAME}');"
R -q -e "roxygen2::roxygenise('${MODEL_NAME}');Rcpp::compileAttributes('${MODEL_NAME}');"

### Install Package Locally ###
rm -f ${MODEL_NAME}/src/*.{so,o}
time R CMD INSTALL --no-multiarch ${MODEL_NAME}
echo


### Run Cpp Unit Tests ###
while getopts ":t" opt
do
  R -q -e "library(${MODEL_NAME}); system.time(${MODEL_NAME}::cytof3_unit_tests_R())"
  R -q -e "library(${MODEL_NAME}); system.time(${MODEL_NAME}::cytof3_unit_tests_cpp())"
done
